### ISSUE TITLE
LED control problem

### ISSUE THREAD

**Issue by GRodolphe** [josh26turner/Ambilight#1]
Hello, 
I would like to thank you in the first place for all the work you have done.

My setup:
Arduino uno
Asus laptop under kali linux
Samsung oddysed G5 screen (which will host the LEDs, only is unique screen)
LED WS2812B
Resolution: 2560x1440
LEDs on the side 26
LEDs on the top 42
Power supply DC 5V 10A
470 ohm resistance between the arduino output and the LED control track

When launching the ambilight command, it seems that the "command" sent to the LEDs seems to be wrong, I have of course changed the arduino code parts to fit my configuration.

Video used to test: https://www.youtube.com/watch?v=8u4UzzJZAUg
Using the video below as a test when the screen is a solid colour the LED's do not all light up in the same colour and some flash in diametrically opposed colours.
I tried to change the value of "pixels_to_process" in the configuration file but nothing helped.

Do you have any idea what is going on?

**Comment by josh26turner** [comment]
Hi,

Could you post your configuration, or any modifications, please?
