### ISSUE TITLE
Error opening connection to Arduino

### ISSUE THREAD

**Issue by TriBallscom** [josh26turner/Ambilight#3]
Hi,

I am running Ubuntu 22.04 on an Intel nuc and use a WS2811 ledstrip. 
Installation went wel, in the Arduino code I only changed the Led type (WS2811) and the NUM_LEDS value.

Any ideas?

**Comment by josh26turner** [comment]
Could you send the actual error that you getting? Are any extra details provided?

I presume the error came from the application running on your Linux machine?

**Comment by TriBallscom** [comment]
That is the actual error when starting ambilight

**Comment by josh26turner** [comment]
Is the device in your `/dev` listing? I.e. does the file `/dev/ttyUSB0` exist. I believe the Arduino IDE should tell you what device filename the USB is connected over, if it differs you can set that in the `~/.config/Ambilight/config` (the `arduino_device_name` setting).

Is your user in the `uucp` group? (`$ groups | grep uucp`) You could try running with sudo to see if that helps.
