### ISSUE TITLE
error on ambilight command

### ISSUE THREAD

**Issue by jibaine** [josh26turner/Ambilight#4]
Hi,
I run the program on archlinux, the ambilight-color command works like a charm but when I try ambilight this error happen:

[gamer@chimeraos ~]$ ambilight
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  7
  Current serial number in output stream:  7

any idea where it can come from?

**Comment by jibaine** [comment]
Ok I get it, ChimeraOS is based on Wayland, it's cetainly why it crashs

**Comment by josh26turner** [comment]
Hi,

Yeah that'll be why, it's good to know what the error message will. Wayland is not supported unfortunately.

The ambilight-color program doesn't interact with the display so will work independently of the desktop setup.

Josh

**Comment by jibaine** [comment]
yes, ambilight-color works fine, I'll try to edit it to adress led independantly (with my very limited C  knowledges^^)  , I don't need something fast, just to apply pattern depending on what run on the computer

**Comment by josh26turner** [comment]
In the history of the repo there are older prototype versions that used a python script and a screenshot utility. Checking out these might yield some of the results you're looking for and work on Wayland 🙂
